# Generated by Django 5.1 on 2024-09-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veggies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
